"""Création table livres

Revision ID: 031bfbf3c367
Revises: a7cda8a7b9c4
Create Date: 2025-07-04 00:09:00.986377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031bfbf3c367'
down_revision = 'a7cda8a7b9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=100), nullable=False),
    sa.Column('auteur', sa.String(length=100), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('date_ajout', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livres')
    # ### end Alembic commands ###
