"""Ajout du modèle Emprunt

Revision ID: aab38d58f5f5
Revises: 8bb71584624d
Create Date: 2025-07-07 17:46:06.655412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab38d58f5f5'
down_revision = '8bb71584624d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emprunts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_emprunteur', sa.String(length=100), nullable=False),
    sa.Column('livre_id', sa.Integer(), nullable=False),
    sa.Column('date_emprunt', sa.Date(), nullable=False),
    sa.Column('rendu', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['livre_id'], ['livres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emprunts')
    # ### end Alembic commands ###
