"""Ajout de nouveaux champ au modele emprint

Revision ID: e13f32d57b33
Revises: aab38d58f5f5
Create Date: 2025-07-07 17:58:57.047726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13f32d57b33'
down_revision = 'aab38d58f5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprunts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifiant_emprunteur', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('telephone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('date_retour_prevue', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprunts', schema=None) as batch_op:
        batch_op.drop_column('date_retour_prevue')
        batch_op.drop_column('email')
        batch_op.drop_column('telephone')
        batch_op.drop_column('identifiant_emprunteur')

    # ### end Alembic commands ###
